services:
  redis:
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  worker:
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy

  scheduler:
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy

  web:
    environment:
      - JOB_ENQUEUE_TOKEN=${JOB_ENQUEUE_TOKEN}
      - IDEMPOTENCY_TTL=${IDEMPOTENCY_TTL}
