name: CI & Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ci-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Login GHCR avec le GITHUB_TOKEN (pas besoin de secrets séparés pour build/push)
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & push web
        run: |
          docker build -t ${REGISTRY}/${OWNER}/diagpilote-web:latest -f backend/Dockerfile backend
          docker push ${REGISTRY}/${OWNER}/diagpilote-web:latest

      - name: Build & push worker (if present)
        if: hashFiles('worker/Dockerfile') != ''
        run: |
          docker build -t ${REGISTRY}/${OWNER}/diagpilote-worker:latest -f worker/Dockerfile worker
          docker push ${REGISTRY}/${OWNER}/diagpilote-worker:latest

      - name: Build & push scheduler (if present)
        if: hashFiles('scheduler/Dockerfile') != ''
        run: |
          docker build -t ${REGISTRY}/${OWNER}/diagpilote-scheduler:latest -f scheduler/Dockerfile scheduler
          docker push ${REGISTRY}/${OWNER}/diagpilote-scheduler:latest

      - name: Build & push nginx (if present)
        if: hashFiles('nginx/Dockerfile') != ''
        run: |
          docker build -t ${REGISTRY}/${OWNER}/diagpilote-nginx:latest -f nginx/Dockerfile nginx
          docker push ${REGISTRY}/${OWNER}/diagpilote-nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH deploy (compose pull + up -d)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}          # clé privée qui ouvre sur le serveur
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -euo pipefail
            cd "${{ secrets.DEPLOY_PATH }}"

            # Login GHCR côté serveur (nécessite GHCR_USERNAME + GHCR_TOKEN en secrets du repo)
            docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" -p "${{ secrets.GHCR_TOKEN }}"

            # Pull (tolérant si un service n'existe pas)
            docker compose -f docker-compose.yml -f docker-compose.override.yml pull web || true
            docker compose -f docker-compose.yml -f docker-compose.override.yml pull worker || true
            docker compose -f docker-compose.yml -f docker-compose.override.yml pull scheduler || true
            docker compose -f docker-compose.yml -f docker-compose.override.yml pull nginx || true

            # Up
            docker compose -f docker-compose.yml -f docker-compose.override.yml up -d

            # Nettoyage & état
            docker image prune -f || true
            docker compose ps
